### ISSUE TITLE
Two app installed

### ISSUE THREAD

**Issue by wikramdas** [kaissaroj/react-native-wallpaper#2]
Hi, i have installed your lib and set as wallpaper working fine, but when I install my app using react-native run-android the system install two apps with same package name. I am having this issue.

**Comment by kaissaroj** [comment]
Sorry for delay reply. Check this [link](https://stackoverflow.com/questions/45196585/two-apps-after-react-native-run-android) . this may help. If not I will update the libary.

**Comment by wikramdas** [comment]
you have to remove this code. I removed these lines error hass been fixed.
<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
</application>

**Comment by wikramdas** [comment]
you have to remove this code. I removed these lines error hass been fixed.
<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
</application>

**Comment by wikramdas** [comment]
you have to remove this code. I removed these lines error hass been fixed.
`<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
</application>`
